package com.dns.configuration;

public class DataProxy {

    public static String Category_Settings = "Do not edit this file unless you know what you are doing!";
    public static String versionurl;
    public static String infourl;
    public static int delay;
}
