package com.dns;

import java.lang.reflect.Method;
import java.util.Arrays;

import com.dns.configuration.Options;
import com.dns.core.handlers.ColourHandler;
import com.dns.core.handlers.VersionHandler;
import com.dns.core.helpers.LogHelper;
import com.dns.core.proxy.CommonProxy;
import com.dns.lib.Reference;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid = Reference.modID, version = Reference.version, name = Reference.modName)
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class DNSUpdater {

    @Instance(Reference.modID)
    public static DNSUpdater instance;

    @SidedProxy(clientSide = Reference.client, serverSide = Reference.common)
    public static CommonProxy proxy;

    @SuppressWarnings({
        "unchecked", "rawtypes"
    })
    @PreInit
    public static void preInit(FMLPreInitializationEvent event) {

        Options.createConfig(event);
        VersionHandler.setType(Reference.type);
        LogHelper.init();
        VersionHandler.init();
        ColourHandler.init();

        event.getModMetadata().authorList = Arrays.asList(new String[] {
                "Darkhax", "MCWizard111", "ShadowChild", "Madcock83"
        });
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().credits = "Maintained by Darkhax, ShadowChild and Madcock83";
        event.getModMetadata().description = "This mod lets you know when the latest DNS packs are released.";

        if(Reference.allowCapeAPI) {
            
            try {

                Class CapeAPI = Class.forName("shadowchild.mod.capeapi.api.CapeAPI");

                Method addCape = CapeAPI.getMethod("addCape", String.class, String.class);
                Method addAdminCape = CapeAPI.getMethod("addAdminCape", String.class, String.class, String[].class);

                addCape.invoke(null, "DNS User!", "http://www.dnstechpack.com/Downloads/capes/UserCape.png");
                addAdminCape.invoke(null, "DNS Staff!", "http://www.dnstechpack.com/Downloads/capes/AdminCape.png", Reference.staff);

                System.out.println("[" + Reference.updaterName + "] " + "CapeAPI Installed, Using That System Instead!");
            } catch(Exception e) {

                System.out.println("[" + Reference.updaterName + "] " + "CapeAPI Not Installed, Defaulting To Own Cape Handling!");
            }
        }

        proxy.registerTickHandler();
    }
}
